_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication4
    - consumer
_workspace: TSBTSOAPTest
consumers:
  - username: DigitalShellApplication4
    custom_id: 95251e00-be8f-2085-9394-6d693f2d194b
    acls: []
