_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_PrimaveraApplication003
    - consumer
_workspace: TSBTSOAPTest
consumers:
  - username: PrimaveraApplication003
    custom_id: 68cef6b9-b920-44f2-a919-043fd3b8ddbd
    acls: []
