_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication8
    - consumer
_workspace: TSBTTest
consumers:
  - username: DigitalShellApplication8
    custom_id: 95251e00-be8f-2089-9394-6d693f2d194b
    acls: []
