_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_tvProgrammerApplication2351069391
    - consumer
_workspace: TSBTTest
consumers:
  - username: tvProgrammerApplication2351069391
    custom_id: 95251e00-be8d-4072-9398-6d693f2d194b
    acls: []
