_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication16
    - consumer
_workspace: TSBTSOAPSAMLTest
consumers:
  - username: DigitalShellApplication16
    custom_id: 95251e00-be8f-2092-9400-6d693f2d194b
    acls: []
