_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication20
    - consumer
_workspace: TSBTSOAPSAMLTest
consumers:
  - username: DigitalShellApplication20
    custom_id: 95251e00-be8f-2092-9404-6d693f2d194b
    acls: []
