_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication9
    - consumer
_workspace: TSBTSOAPSAMLTest
consumers:
  - username: DigitalShellApplication9
    custom_id: 95251e00-be8f-2091-9394-6d693f2d194b
    acls: []
