_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication26
    - consumer
_workspace: TSBTSOAPTest
consumers:
  - username: DigitalShellApplication26
    custom_id: 95251e00-be8f-2092-9410-6d693f2d194b
    acls: []
