_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication33
    - consumer
_workspace: TSBTLegacyTest
consumers:
  - username: DigitalShellApplication33
    custom_id: 95251e00-be8f-2092-9417-6d693f2d194b
    acls: []
