_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication13
    - consumer
_workspace: TSBTSOAPSAMLTest
consumers:
  - username: DigitalShellApplication13
    custom_id: 95251e00-be8f-2092-9397-6d693f2d194b
    acls: []
