_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication11
    - consumer
_workspace: TSBTSOAPSAMLTest
consumers:
  - username: DigitalShellApplication11
    custom_id: 95251e00-be8f-2092-9395-6d693f2d194b
    acls: []
