_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication37
    - consumer
_workspace: TelusDigitalTest
consumers:
  - username: DigitalShellApplication37
    custom_id: 95251e00-be8f-2092-9421-6d693f2d194b
    acls: []
