_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_tvProgrammerApplication2351069374
    - consumer
_workspace: TelusDigitalTest
consumers:
  - username: tvProgrammerApplication2351069374
    custom_id: 2000d3a9-a9a2-414d-8c62-ca033aa74571
    acls: []
