_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_tvProgrammerApplication235101200
    - consumer
_workspace: TSBTSOAPTest
consumers:
  - username: tvProgrammerApplication235101200
    custom_id: 95251e01-be8d-4076-9398-6d693f2d194b
    acls: []
    basicauth_credentials:
      - password: $SECRET_tvProgrammerApplication235101200_NP$
        username: 95251E01-BE8D-4076-9398-6D693F2D194B
