_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - lobbyistApplication9928833095
    - service
_workspace: lobbyistApplication9928833095
services:
  - name: lobbyistApplication9928833095
    host: api-marketplace-ng-portal-ui-dev.api-marketplace-ng-ui.svc.cluster.local
    path: /v1
    port: 3000
    protocol: http
    retries: 2
    plugins: []
    routes:
      - name: lobbyistApplication9928833095_tm
        protocols:
          - https
        paths:
          - /v1
        methods: []
        hosts:
          - api-marketplace-ng-dv.cloudapps.telus.com
        preserve_host: true
        regex_priority: 0
        strip_path: true
        plugins:
          - name: openid-connect
            config:
              login_methods:
                - authorization_code
              login_tokens: []
              token_endpoint: https://apigw-st.telus.com/st/token
              token_endpoint_auth_method: client_secret_basic
              auth_methods:
                - password
                - client_credentials
                - authorization_code
                - bearer
                - introspection
                - kong_oauth2
                - refresh_token
                - session
              redirect_uri:
                - https://api-marketplace-ng-dv.cloudapps.telus.com/v1
              client_id:
                - e5ead549-35c5-4f92-8e4d-a08175c6dedd
              client_secret:
                - $SECRET_lobbyistApplication9928833095_tm_NP$
              cache_token_exchange: true
              introspect_jwt_tokens: true
              forbidden_destroy_session: true
              session_cookie_httponly: true
              session_cookie_name: lobbyistApplication9928833095-session
              session_cookie_idletime: 28800
              session_cookie_lifetime: 28800
              session_cookie_domain: api-marketplace-ng-dv.cloudapps.telus.com
              authorization_cookie_domain: api-marketplace-ng-dv.cloudapps.telus.com
              keepalive: true
              preserve_query_args: true
              authorization_cookie_httponly: true
              authorization_cookie_name: lobbyistApplication9928833095-authz
              authorization_cookie_lifetime: 28800
              authorization_endpoint: https://teamsso-its04.telus.com/as/authorization.oauth2
              password_param_type:
                - header
                - query
                - body
              cache_introspection: true
              cache_tokens: true
              cache_user_info: true
              extra_jwks_uris:
                - https://apigw-st.telus.com/st/jwks
                - https://apigw-st.telus.com/st/id/jwks
              consumer_by: []
              verify_claims: true
              consumer_claim: []
              id_token_param_type:
                - header
                - query
                - body
              credential_claim:
                - sub
              issuer: https://teamsso-its04.telus.com
              verify_nonce: true
              scopes_claim:
                - scope
              upstream_id_token_header: x-id-token
              upstream_headers_claims:
                - iss
              upstream_headers_names:
                - iss
              upstream_access_token_header: authorization:bearer
              refresh_token_param_type:
                - header
                - query
                - body
              client_credentials_param_type:
                - header
                - query
                - body
              audience_claim:
                - aud
              audience_required:
                - kong
              verify_signature: true
              scopes_required:
                - openid
                - profile
                - email
              scopes:
                - openid
                - profile
                - email
              client_arg: client_id
              login_action: redirect
              bearer_token_param_type:
                - header
              session_redis_port: 6379
              session_redis_ssl: false
              session_redis_ssl_verify: false
              session_redis_prefix: sessions
              session_redis_host: 10.64.0.12
              session_storage: redis
      - name: lobbyistApplication9928833095_ci
        protocols:
          - https
        paths:
          - /v1
        methods: []
        hosts:
          - api-marketplace-ng-it-customer-test.cloudapps.telus.com
        preserve_host: true
        regex_priority: 0
        strip_path: true
        plugins:
          - name: openid-connect
            config:
              login_methods:
                - authorization_code
              login_tokens: []
              auth_methods:
                - password
                - client_credentials
                - authorization_code
                - bearer
                - introspection
                - kong_oauth2
                - refresh_token
                - session
              redirect_uri:
                - https://api-marketplace-ng-it-customer-test.cloudapps.telus.com/v1
              client_id:
                - e5ead549-35c5-4f92-8e4d-a08175c6dedd
              client_secret:
                - $SECRET_lobbyistApplication9928833095_ci_NP$
              cache_token_exchange: true
              introspect_jwt_tokens: true
              forbidden_destroy_session: true
              session_cookie_httponly: true
              session_cookie_name: lobbyistApplication9928833095-session
              session_cookie_idletime: 28800
              session_cookie_lifetime: 28800
              session_cookie_domain: api-marketplace-ng-it-customer-test.cloudapps.telus.com
              authorization_cookie_domain: api-marketplace-ng-it-customer-test.cloudapps.telus.com
              keepalive: true
              preserve_query_args: true
              authorization_cookie_httponly: true
              authorization_cookie_name: lobbyistApplication9928833095-authz
              authorization_cookie_lifetime: 28800
              password_param_type:
                - header
                - query
                - body
              cache_introspection: true
              cache_tokens: true
              cache_user_info: true
              extra_jwks_uris:
                - null
              consumer_by: []
              verify_claims: true
              consumer_claim: []
              id_token_param_type:
                - header
                - query
                - body
              credential_claim:
                - sub
              verify_nonce: true
              scopes_claim:
                - scope
              upstream_id_token_header: x-id-token
              upstream_headers_claims:
                - iss
              upstream_headers_names:
                - iss
              upstream_access_token_header: authorization:bearer
              refresh_token_param_type:
                - header
                - query
                - body
              client_credentials_param_type:
                - header
                - query
                - body
              audience_claim:
                - aud
              audience_required:
                - kong
              verify_signature: true
              scopes_required:
                - openid
                - profile
                - email
              scopes:
                - openid
                - profile
                - email
              client_arg: client_id
              login_action: redirect
              bearer_token_param_type:
                - header
              authorization_query_args_names:
                - env
              authorization_query_args_values:
                - it02
              session_redis_port: 6379
              session_redis_ssl: false
              session_redis_ssl_verify: false
              session_redis_prefix: sessions
              session_redis_host: 10.64.0.12
              session_storage: redis
