_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication7
    - consumer
_workspace: TSBTTest
consumers:
  - username: DigitalShellApplication7
    custom_id: 95251e00-be8f-2088-9394-6d693f2d194b
    acls: []
