_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_tvProgrammerApplication235101200
    - consumer
_workspace: TSBTTest
consumers:
  - username: tvProgrammerApplication235101200
    custom_id: 95251e01-be8d-4076-9398-6d693f2d194b
    acls: []
