_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_tvProgrammerApplication2351069393
    - consumer
_workspace: TSBTTest
consumers:
  - username: tvProgrammerApplication2351069393
    custom_id: 95251e00-be8d-4074-9398-6d693f2d194b
    acls: []
