_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication38
    - consumer
_workspace: TSBTTest
consumers:
  - username: DigitalShellApplication38
    custom_id: 95251e00-be8f-2092-9422-6d693f2d194b
    acls: []
