_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_flightEngineerApplication2006799274
    - consumer
_workspace: TSBTTest
consumers:
  - username: flightEngineerApplication2006799274
    custom_id: 56756436-15ef-45fd-b2c9-1040d07aab2a
    acls: []
