_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication40
    - consumer
_workspace: TelusDigitalTest
consumers:
  - username: DigitalShellApplication40
    custom_id: 95251e00-be8f-2092-9425-6d693f2d194b
    acls: []
