_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_databaseManagerApplication5734244557
    - consumer
_workspace: TelusDigitalTest
consumers:
  - username: databaseManagerApplication5734244557
    custom_id: b8df7463-132c-4256-8ee0-536a52685835
    acls: []
