_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_tvProgrammerApplication2351069377
    - consumer
_workspace: TSBTSOAPSAMLTest
consumers:
  - username: tvProgrammerApplication2351069377
    custom_id: 95251e00-be8e-4072-9394-6d693f2d194b
    acls: []
    basicauth_credentials:
      - password: $SECRET_tvProgrammerApplication2351069377_NP$
        username: 95251E00-BE8E-4072-9394-6D693F2D194B
