_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication18
    - consumer
_workspace: TSBTTest
consumers:
  - username: DigitalShellApplication18
    custom_id: 95251e00-be8f-2092-9402-6d693f2d194b
    acls: []
