_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_tvProgrammerApplication23510693772
    - consumer
_workspace: TSBTTest
consumers:
  - username: tvProgrammerApplication23510693772
    custom_id: 95251e00-be8e-4072-9392-6d693f2d194b
    acls: []
