_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication27
    - consumer
_workspace: TSBTLegacyTest
consumers:
  - username: DigitalShellApplication27
    custom_id: 95251e00-be8f-2092-9411-6d693f2d194b
    acls: []
