_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_tvProgrammerApplication2351069373
    - consumer
_workspace: TSBTLegacyTest
consumers:
  - username: tvProgrammerApplication2351069373
    custom_id: 664f6c12-96aa-469e-bd80-bcc2d795b268
    acls: []
