_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_tvProgrammerApplication2351069392
    - consumer
_workspace: TSBTLegacyTest
consumers:
  - username: tvProgrammerApplication2351069392
    custom_id: 95251e00-be8d-4073-9398-6d693f2d194b
    acls: []
    basicauth_credentials:
      - password: $SECRET_tvProgrammerApplication2351069392_NP$
        username: 95251E00-BE8D-4073-9398-6D693F2D194B
