_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_tvProgrammerApplication2351069369
    - consumer
_workspace: TSBTLegacyTest
consumers:
  - username: tvProgrammerApplication2351069369
    custom_id: f1515037-7d90-4b27-a0a7-3e1fcc775f8e
    acls: []
