_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication24
    - consumer
_workspace: TSBTLegacyTest
consumers:
  - username: DigitalShellApplication24
    custom_id: 95251e00-be8f-2092-9408-6d693f2d194b
    acls: []
