_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication5
    - consumer
_workspace: TSBTLegacyTest
consumers:
  - username: DigitalShellApplication5
    custom_id: 95251e00-be8f-2086-9394-6d693f2d194b
    acls: []
