_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication39
    - consumer
_workspace: TSBTLegacyTest
consumers:
  - username: DigitalShellApplication39
    custom_id: 95251e00-be8f-2092-9423-6d693f2d194b
    acls: []
