_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication10
    - consumer
_workspace: TSBTSOAPSAMLTest
consumers:
  - username: DigitalShellApplication10
    custom_id: 95251e00-be8f-2092-9394-6d693f2d194b
    acls: []
