_format_version: '1.1'
_info:
  defaults: {}
  select_tags:
    - app_DigitalShellApplication25
    - consumer
_workspace: TSBTSOAPTest
consumers:
  - username: DigitalShellApplication25
    custom_id: 95251e00-be8f-2092-9409-6d693f2d194b
    acls: []
